ACCEPT:
  - json

max_workers: 100

DB_URIS:
  'integrations:Base': mysql+mysqlconnector://${DB_USER:root}:${DB_PASS:}@${DB_SERVER:localhost}/${DB_NAME:g_integrations}

SYSTEM_DEFAULT_USER:
  ID: ${SYSTEM_DEFAULT_USER_ID:1}
  EMAIL: ${SYSTEM_DEFAULT_USER_EMAIL:default@student.com}
  PASSWORD: ${SYSTEM_DEFAULT_USER_PASSWORD:password}

DB_POOL_SIZE: 3
DB_POOL_RECYCLE: 7200
DB_MAX_OVERFLOW: 100

UPDATE_SERIAL_ENABLED: False


WEB_SERVER_ADDRESS: ${WEB_SERVER_ADDRESS:0.0.0.0:8089}

AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASS:guest}@${RABBIT_SERVER:localhost}:${RABBIT_PORT:5672}/${RABBIT_VHOST:}

REDIS_URI: redis://${REDIS_SERVER:localhost}:${REDIS_PORT:6379}/${REDIS_DB:1}


VERSION_FILE: ${VERSION_FILE:version.json}

JWT_SECRET: ${JWT_SECRET:secret}

ENTRYPOINT_BLACKLIST: ${ENTRYPOINT_BLACKLIST:}
